Add test cases for ansi
muesli/reflow pull request #4
Opened 2020-10-14 07:39 UTC by kiyonlin

Hey @muesli I'm a fan of `bubbletea` now 😄  Thanks for your awesome work!

And I found `reflow` have room for performance improvement and test coverage. 

I plan to improve them step by step.

This PR only added test cases for asni. If you accept it, I'll do the improvement work.

2020-10-18 21:09 UTC, muesli requested changes
Sorry for the delayed review @kiyonlin, the last few days have been super hectic :smiley:

Looks good to me, just a few nitpicky change requests. Thank you for contributing!

2020-10-18 21:09 UTC, muesli commented on ansi/writer_test.go
> +
Spurious newline.

2020-10-18 21:09 UTC, muesli commented on ansi/writer_test.go
> +		t.Fatal("err shouldn't be nil")
We should probably print out the error that we got instead of `nil`.

2020-10-18 21:09 UTC, muesli commented on ansi/writer_test.go
> +		b.Fatal("err should be nil")
We should probably print out the error that we got instead of nil.

2020-10-18 21:09 UTC, muesli commented on ansi/writer_test.go
> +		t.Fatal("err should be nil")
We should probably print out the error that we got instead of nil.

2020-10-19 00:48 UTC, kiyonlin commented
Thanks for your detail review 😄 

> Sorry for the delayed review @kiyonlin, the last few days have been super hectic 😃

You guys are famous now 👍

2020-10-19 01:21 UTC, merged